name: Feature request
description: Suggest an idea or enhancement for zizmor-vscode
title: "Feature: "
labels:
  - enhancement
  - triage
body:
  - type: markdown
    attributes:
      value: |
        Thanks for making a `zizmor` feature request!

        Please read the following parts of this form **very carefully**.
        Invalid or incomplete submissions take longer to triage,
        and may be given a lower priority or closed outright
        if not actionable.

  - type: checkboxes
    attributes:
      label: Pre-submission checks
      description: |
        By submitting this issue, you affirm that you've satisfied the following conditions.
      options:
        - label: >-
            I am **not** reporting a bug (crash, false positive/negative, etc).
            These must be filed via the bug report template.
          required: true
        - label: >-
            I am filing an issue for **zizmor-vscode**, not for zizmor itself.
            Feature requests for zizmor should be filed against
            [zizmorcore/zizmor](https://github.com/zizmorcore/zizmor/issues).
        - label: >-
            I have looked through both the
            [open](https://github.com/zizmorcore/zizmor-vscode/issues?q=is%3Aissue+is%3Aopen+)
            and [closed](https://github.com/zizmorcore/zizmor-vscode/issues?q=is%3Aissue%20state%3Aclosed)
            issues for a duplicate request.
          required: true

  - type: textarea
    attributes:
      label: What's the problem this feature will solve?
      description: |
        A clear and concise description of the problem.
      placeholder: |
        I'm always frustrated when ...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional context
      description: |
        Any additional context, screenshots, or other material about the feature request.
